apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelinesjavascriptdocker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: pipelinesjavascriptdocker
    spec:
      containers:
      - name: pipelinesjavascriptdocker
        image: aali500acr.azurecr.io/drewontechpipelinesjavascriptdocker
        ports:
        - containerPort: 8080
